import React from "react";
import "../styles/Disclaimer.scss";

export default function Disclaimer() {
  return (
    <div className="container">
      <div className="text-wrapper">
        <div className="disclaimer">
          <h3>Disclaimer</h3>
          <p>
            Patodia Infotech Private Limited (fastdevai.com) has no
            responsibility for any text or code generated or for any action
            taken by you based on the contents provided by this web site. The
            use of this web site is solely at the user's risk. All the services
            are provided with the understanding that Patodia Infotech Private
            Limited or any other person or company associated with this company
            or website are not responsible for any loss or damage occurring to
            anybody from any code or contents generated by this website. Please
            note that text, codes and contents are generated by AI. These are
            state-of-the-art AI solutions. However, these are AI tools so there
            is no guarantee of accuracy of any code or contents generated.
          </p>
        </div>
      </div>
    </div>
  );
}
